name: Report coverage

on:
  push:
    branches:
      - '**'  # any branch
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: Merge coverage
        run: mvn jacoco:merge@merge-id -pl starts-core

      - name: Report
        run: mvn jacoco:report@report-id -pl starts-core

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: starts-core/target/site/jacoco-merged/jacoco.csv
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Add comment to PR
        uses: mshick/add-pr-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
          message: 'Statement coverage = ${{ steps.jacoco.outputs.coverage }}

                    Branch coverage = ${{ steps.jacoco.outputs.branches }}'
